nestjs/throttler

README.md
package.json
src/throttler-core.module.ts
src/throttler.module.ts
test/app/app.module.ts
test/app/controllers/controller.module.ts
test/controller.e2e-spec.ts
yarn.lock

This PR will change the module from auto-binding the guard globally to allowing the user to define how to bind the guard. Reasons for doing this:
1) not all routes should be rate limited
2) allows the user to extend the guards functionality
3) better customization of the package overall

feat(guard): changes guard from global to user defined

---

.commitlintrc.json
commitlint.config.js
package.json
yarn.lock

chore(): update configuration commitlint

---

src/throttler.exception.ts
src/throttler.guard.ts

@amit-sharma-dev thoughts on this? You'd essentially be able to do something like
```ts
@Injectable()
export class CustomThrottlerGuard extends ThrottlerGuard {
protected message = 'My Custom Throttler Message':
}
```
And the custom error message should take.

feat(exception): allow for customization of thrown exception from guard

---

src/throttler.guard.ts

Resolves #531.
I am unsure about:
- the name of the `throwException` vs `throwThrottlerException` vs
`throwThrottlingException` method. In the end I decided to use
`throwThrottlingException` because it's more precise than
`throwException` and `throwThrottlerException` sounds like one is
always throwing `ThrottlerException`, which is not the case when
overriding the method (but not a strong opinion).
- the line with "eslint-disable-next-line...". I added `context` as
a parameter because of your comment @jmcdo29, but since I see no
point in using `context` for the default case, I had to disable
eslint for the line. I don't know if this is against any practices
of this project.

feat: Add throwThrottlingException method

---

.github/ISSUE_TEMPLATE/Bug_report.yml
.github/ISSUE_TEMPLATE/Feature_request.yml
.github/ISSUE_TEMPLATE/Regression.yml
.github/ISSUE_TEMPLATE/config.yml
.github/PULL_REQUEST_TEMPLATE.md

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe:
```
Just because GitHub issue forms looks nicer than the old issue templates, and also to enforce for sure some standard across issues in this repo.
See them in action here: https://github.com/micalevisk/throttler/issues/new/choose
Adds the same pull request template and the same issue forms as the ones in these others @nestjs repos, with minor changes:
```
[ ] Yes
[x] No
```

chore(): add github issue and pull request templates

---

README.md

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe:
```
Update the `README.md` file with some improvements.
```
[ ] Yes
[x] No
```
This PR, update the `README.md` file with some improvements.

docs(): update readme.md

---

.changeset/beige-guests-develop.md
src/throttler.service.ts

Timeout Ids are not deleted and array is growing cont. causing heap memory issues.
Timeout Ids are not deleted and array is growing cont. causing heap memory issues.
Timeout Ids are deleted from array on timeout callback.

Fix(service): Memory leak in in service timeoutIds array

---

LICENSE
README.md

Update logo in readme and license
Update logo in readme and license( A small and quick update 😁)

docs(readme): update logo in readme and license

---

.changeset/twenty-trees-sneeze.md
.husky/commit-msg
yarn.lock

Major bump for @nestjs/common@9 release
Technically works on v9 without official support
Works on v9 with official support
No real breaking change, backwards compatibility is there, but this keeps with the idea of bumping majors all together

chore: update yarn lock for nest v9

---

src/throttler-module-options.interface.ts
src/throttler.decorator.ts
src/throttler.guard.ts
src/throttler.service.ts

Proposals:
- Added annotation `@publicApi` in `throttler-module-options.interface.ts` and `throttler.service.ts`
- Update annotation JSdoc 
If there are private APIs that are not public, which I forgot, please let me know so I can update the PR.

chore(): mark api public and update annotations jsdoc

---

.changeset/light-emus-grab.md
README.md
src/throttler-module-options.interface.ts
src/throttler.decorator.ts
src/throttler.guard.spec.ts
src/throttler.guard.ts

Issue Number: #1483
Enable configuring `ttl` and `limit` with a callback function, in order to enable custom limits/ttl per user, IP...

feat: contextual options

---

.changeset/rude-teachers-drop.md
README.md
src/throttler-module-options.interface.ts
src/throttler.decorator.ts
src/throttler.guard.spec.ts
src/throttler.guard.ts

Reverts nestjs/throttler#1484
ref: #1566
Will be re-added in 5.0.0

revert: "feat: contextual options"

---

README.md

fix: docs typo `long` key should be `name`

---

README.md

The code provided did not work, so I corrected the example code to work.
Not so important. Just a little typo

Fixed README.md file, replaced request with req as in method parameters.

---

README.md

Updated the ThrottlerGuard documentation to include instructions on configuring the GraphQL context for proper functioning. Added details about creating a custom GqlThrottlerGuard and highlighted the importance of setting up the context in the GraphQLModule to avoid potential issues.
- [ x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x ] Tests for the changes have been added (for bug fixes / features)
- [ x] Docs have been added / updated (for bug fixes / features)
- [x ] Refactoring (no functional changes, no api changes)
Issue Number: #1110
More documentation in the README
- [x ] No

docs: Add instructions for configuring GraphQL context

---

README.md

Added a 'Back to Top' button in readme to enhance navigation while reading.

docs: Added a 'Back to Top" button

---

README.md

Document the newer usage with v5 and websockets
Issue Number: closes #1672

docs: update websocket usage documentation

---

.changeset/purple-icons-protect.md
README.md
src/throttler-module-options.interface.ts
src/throttler.guard.ts
test/error-message/app.module.ts
test/error-message/custom-error-message.controller.ts
test/error-message/custom-error-message.e2e-spec.ts

One can pass a static errorMessage as string to the ThrottlerModuleOptions or it is defaulted to a static string.
One can pass either a static errorMessage as string OR a function to generate an error message based on the current context to the ThrottlerModuleOptions or it is defaulted to a static string.
I personally think this is important in order to track on which routes and for what users rate limiting occurs.

feat(core): add dynamic error messages

---

.changeset/clever-elephants-cough.md
.github/workflows/ci.yml
.husky/commit-msg
.husky/pre-commit
package.json
pnpm-lock.yaml
src/throttler.service.ts
test/controller.e2e-spec.ts

Issue Number: #2074
Also updates husky and the pnpm lockfile to newer verison

fix: properly calculate expireAt and blockExpireAt using `ceil` instead of `floor`

---

.changeset/thick-penguins-change.md
README.md

Docs are outdated for websockets
Issue Number: #2047 
Docs are updated for websockets

chore: update websocket readme
